---
title: "Mean Revision Strategies"
author: "Paul Nheera"
date: '2022-07-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
#Libraries:
library(readr)
library(ggplot2)
library(plotly)
library(quantmod)
library(dplyr)
library(PerformanceAnalytics)
```


```{r}
# Import data:
data <- read_csv("Kucoin_BTCUSDT_1H.csv")

#market_data
#indicators
#market_stats - e.g. return, std dev, etc
data$Time = as.POSIXct(data$Time, format="%d/%m/%Y %H:%M")
head(data)
```


```{r}
# Plot the closing price:
p <- ggplot(data, aes(x=Time,y=Close))+
  geom_line(col='blue') +
  ggtitle('Closing price')

p
```


#### Mean reversion strategy


```{r}
k <- 20
threshold <- 2.5 # standard deviations

# Add Bollinger Bands
BBands <- BBands(data$Close, n=k, sd=threshold)

data = data.frame(data,BBands)
```


```{r Positions}

# short positions
data <- data %>% 
  mutate(position = ifelse(Close > up , -1, NA))

# long positions
data <- data %>% 
  mutate(position = ifelse(Close < dn , 1, position))

# exits
data <- data %>% 
  mutate(dist = Close - mavg)
data <- data %>% 
  mutate(position =ifelse(dist*lag(dist) < 0 , 0,position))

# fill in the rest of the positions:
data <- data %>% 
  mutate(position = na.locf(position,na.rm = FALSE))

# replace remaining NAs with zeros
data <- data %>% 
  mutate(position = ifelse(is.na(position),0,position))

```


```{r}
# Plot the positions
ggplot(data, aes(x=Time, y=position)) +
  geom_line(col='blue')
```


```{r Strategy returns}

# Calculate asset returns
data <- data %>% 
  mutate(returns = ROC(Close,type='discrete'))

# Determine strategy returns

## First lag the positions vector (avoid look-ahead bias)
data <- data %>% 
  mutate(position = lag(position)) %>% 
  mutate(position = ifelse(is.na(position),0,position))

data <- data %>% 
  mutate(strat_ret = position * returns)

```


```{r}
# Performance Chart
strat_ret = as.xts(data$strat_ret,order.by = data$Time)

charts.PerformanceSummary(strat_ret)
```

```{r}
# Evaluate Performance

Return.cumulative(strat_ret)
```









